/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attestAiDecisionSol from "./AttestAIDecision.sol";
export type { attestAiDecisionSol };
export type { MockVerifier } from "./MockVerifier";
export type { SignalEmitter } from "./SignalEmitter";
