/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MockVerifier {
  export type MerkleProofEntryStruct = { hash: BytesLike; isLeft: boolean };

  export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {
    hash: string;
    isLeft: boolean;
  };

  export type MerkleProofStruct = {
    root: BytesLike;
    siblings: MockVerifier.MerkleProofEntryStruct[];
  };

  export type MerkleProofStructOutput = [
    root: string,
    siblings: MockVerifier.MerkleProofEntryStructOutput[]
  ] & { root: string; siblings: MockVerifier.MerkleProofEntryStructOutput[] };

  export type ContinuityProofStruct = {
    lowerEndpointDigest: BytesLike;
    roots: BytesLike[];
  };

  export type ContinuityProofStructOutput = [
    lowerEndpointDigest: string,
    roots: string[]
  ] & { lowerEndpointDigest: string; roots: string[] };
}

export interface MockVerifierInterface extends Interface {
  getFunction(nameOrSignature: "result" | "verify"): FunctionFragment;

  encodeFunctionData(functionFragment: "result", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      MockVerifier.MerkleProofStruct,
      MockVerifier.ContinuityProofStruct
    ]
  ): string;

  decodeFunctionResult(functionFragment: "result", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export interface MockVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): MockVerifier;
  waitForDeployment(): Promise<this>;

  interface: MockVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  result: TypedContractMethod<[], [boolean], "view">;

  verify: TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BytesLike,
      arg3: MockVerifier.MerkleProofStruct,
      arg4: MockVerifier.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "result"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BytesLike,
      arg3: MockVerifier.MerkleProofStruct,
      arg4: MockVerifier.ContinuityProofStruct
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
