/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SignalEmitterInterface extends Interface {
  getFunction(nameOrSignature: "emitSignal" | "nextSignalId"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MarketSignal"): EventFragment;

  encodeFunctionData(
    functionFragment: "emitSignal",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextSignalId",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "emitSignal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextSignalId",
    data: BytesLike
  ): Result;
}

export namespace MarketSignalEvent {
  export type InputTuple = [
    signalId: BigNumberish,
    asset: BytesLike,
    price: BigNumberish,
    liquidity: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    signalId: bigint,
    asset: string,
    price: bigint,
    liquidity: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    signalId: bigint;
    asset: string;
    price: bigint;
    liquidity: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SignalEmitter extends BaseContract {
  connect(runner?: ContractRunner | null): SignalEmitter;
  waitForDeployment(): Promise<this>;

  interface: SignalEmitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emitSignal: TypedContractMethod<
    [asset: BytesLike, price: BigNumberish, liquidity: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  nextSignalId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "emitSignal"
  ): TypedContractMethod<
    [asset: BytesLike, price: BigNumberish, liquidity: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextSignalId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "MarketSignal"
  ): TypedContractEvent<
    MarketSignalEvent.InputTuple,
    MarketSignalEvent.OutputTuple,
    MarketSignalEvent.OutputObject
  >;

  filters: {
    "MarketSignal(uint256,bytes32,int256,uint256,uint256)": TypedContractEvent<
      MarketSignalEvent.InputTuple,
      MarketSignalEvent.OutputTuple,
      MarketSignalEvent.OutputObject
    >;
    MarketSignal: TypedContractEvent<
      MarketSignalEvent.InputTuple,
      MarketSignalEvent.OutputTuple,
      MarketSignalEvent.OutputObject
    >;
  };
}
