/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "EvmV1Decoder",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EvmV1Decoder__factory>;
    getContractFactory(
      name: "AttestAIDecision",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AttestAIDecision__factory>;
    getContractFactory(
      name: "INativeQueryVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.INativeQueryVerifier__factory>;
    getContractFactory(
      name: "MockVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockVerifier__factory>;
    getContractFactory(
      name: "SignalEmitter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SignalEmitter__factory>;

    getContractAt(
      name: "EvmV1Decoder",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EvmV1Decoder>;
    getContractAt(
      name: "AttestAIDecision",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AttestAIDecision>;
    getContractAt(
      name: "INativeQueryVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.INativeQueryVerifier>;
    getContractAt(
      name: "MockVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockVerifier>;
    getContractAt(
      name: "SignalEmitter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SignalEmitter>;

    deployContract(
      name: "EvmV1Decoder",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EvmV1Decoder>;
    deployContract(
      name: "AttestAIDecision",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AttestAIDecision>;
    deployContract(
      name: "INativeQueryVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INativeQueryVerifier>;
    deployContract(
      name: "MockVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockVerifier>;
    deployContract(
      name: "SignalEmitter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignalEmitter>;

    deployContract(
      name: "EvmV1Decoder",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EvmV1Decoder>;
    deployContract(
      name: "AttestAIDecision",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AttestAIDecision>;
    deployContract(
      name: "INativeQueryVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.INativeQueryVerifier>;
    deployContract(
      name: "MockVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockVerifier>;
    deployContract(
      name: "SignalEmitter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignalEmitter>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
