/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockVerifier,
  MockVerifierInterface,
} from "../../contracts/MockVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "initialResult",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "result",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "hash",
                type: "bytes32",
              },
              {
                internalType: "bool",
                name: "isLeft",
                type: "bool",
              },
            ],
            internalType: "struct MockVerifier.MerkleProofEntry[]",
            name: "siblings",
            type: "tuple[]",
          },
        ],
        internalType: "struct MockVerifier.MerkleProof",
        name: "",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "lowerEndpointDigest",
            type: "bytes32",
          },
          {
            internalType: "bytes32[]",
            name: "roots",
            type: "bytes32[]",
          },
        ],
        internalType: "struct MockVerifier.ContinuityProof",
        name: "",
        type: "tuple",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608034606257601f6101ef38819003918201601f19168301916001600160401b038311848410176067578084926020946040528339810103126062575180151580910360625760ff801960005416911617600055604051610171908161007e8239f35b600080fd5b634e487b7160e01b600052604160045260246000fdfe608080604052600436101561001357600080fd5b60003560e01c90816365372147146100ed5750637cc4e2581461003557600080fd5b346100e85760a03660031901126100e85761004e61010d565b50610057610124565b5060443567ffffffffffffffff81116100e857366023820112156100e857806004013567ffffffffffffffff81116100e857369101602401116100e85760643567ffffffffffffffff81116100e85760409060031990360301126100e85760843567ffffffffffffffff81116100e85760409060031990360301126100e857602060ff600054166040519015158152f35b600080fd5b346100e85760003660031901126100e85760209060ff6000541615158152f35b6004359067ffffffffffffffff821682036100e857565b6024359067ffffffffffffffff821682036100e85756fea26469706673582212201fe2ef5c940dbc76c9fcedc99b6973cb32f05d6a72d64c4acf53339f46f5994b64736f6c634300081c0033";

type MockVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockVerifier__factory extends ContractFactory {
  constructor(...args: MockVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    initialResult: boolean,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(initialResult, overrides || {});
  }
  override deploy(
    initialResult: boolean,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(initialResult, overrides || {}) as Promise<
      MockVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockVerifier__factory {
    return super.connect(runner) as MockVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockVerifierInterface {
    return new Interface(_abi) as MockVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockVerifier {
    return new Contract(address, _abi, runner) as unknown as MockVerifier;
  }
}
