/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  SignalEmitter,
  SignalEmitterInterface,
} from "../../contracts/SignalEmitter";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "signalId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "asset",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "int256",
        name: "price",
        type: "int256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "MarketSignal",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "asset",
        type: "bytes32",
      },
      {
        internalType: "int256",
        name: "price",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "liquidity",
        type: "uint256",
      },
    ],
    name: "emitSignal",
    outputs: [
      {
        internalType: "uint256",
        name: "signalId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "nextSignalId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234601557610106908161001b8239f35b600080fdfe6080806040526004361015601257600080fd5b60003560e01c9081635edc95dd146053575063b0c3b8ef14603257600080fd5b34604e576000366003190112604e576020600054604051908152f35b600080fd5b34604e576060366003190112604e57600054600019811460ba5760209160018201600055602435815260443583820152426040820152817f860df55fb85f652cffc93995f34b6f373ccc3ce7abf5e78b9eff8c9e454cd33d606060043593a3604051908152f35b634e487b7160e01b600052601160045260246000fdfea2646970667358221220cbd66e647e0d26e46eb0fd9021f46abd3cddb323e8ef3cd5faf2e987c0ff438964736f6c634300081c0033";

type SignalEmitterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SignalEmitterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SignalEmitter__factory extends ContractFactory {
  constructor(...args: SignalEmitterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SignalEmitter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SignalEmitter__factory {
    return super.connect(runner) as SignalEmitter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SignalEmitterInterface {
    return new Interface(_abi) as SignalEmitterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SignalEmitter {
    return new Contract(address, _abi, runner) as unknown as SignalEmitter;
  }
}
