/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INativeQueryVerifier,
  INativeQueryVerifierInterface,
} from "../../../contracts/AttestAIDecision.sol/INativeQueryVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "chainKey",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "height",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "encodedTransaction",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "root",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "hash",
                type: "bytes32",
              },
              {
                internalType: "bool",
                name: "isLeft",
                type: "bool",
              },
            ],
            internalType: "struct INativeQueryVerifier.MerkleProofEntry[]",
            name: "siblings",
            type: "tuple[]",
          },
        ],
        internalType: "struct INativeQueryVerifier.MerkleProof",
        name: "merkleProof",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "bytes32",
            name: "lowerEndpointDigest",
            type: "bytes32",
          },
          {
            internalType: "bytes32[]",
            name: "roots",
            type: "bytes32[]",
          },
        ],
        internalType: "struct INativeQueryVerifier.ContinuityProof",
        name: "continuityProof",
        type: "tuple",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class INativeQueryVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): INativeQueryVerifierInterface {
    return new Interface(_abi) as INativeQueryVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INativeQueryVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as INativeQueryVerifier;
  }
}
