/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace INativeQueryVerifier {
  export type MerkleProofEntryStruct = { hash: BytesLike; isLeft: boolean };

  export type MerkleProofEntryStructOutput = [hash: string, isLeft: boolean] & {
    hash: string;
    isLeft: boolean;
  };

  export type MerkleProofStruct = {
    root: BytesLike;
    siblings: INativeQueryVerifier.MerkleProofEntryStruct[];
  };

  export type MerkleProofStructOutput = [
    root: string,
    siblings: INativeQueryVerifier.MerkleProofEntryStructOutput[]
  ] & {
    root: string;
    siblings: INativeQueryVerifier.MerkleProofEntryStructOutput[];
  };

  export type ContinuityProofStruct = {
    lowerEndpointDigest: BytesLike;
    roots: BytesLike[];
  };

  export type ContinuityProofStructOutput = [
    lowerEndpointDigest: string,
    roots: string[]
  ] & { lowerEndpointDigest: string; roots: string[] };
}

export interface AttestAIDecisionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MARKET_SIGNAL_EVENT"
      | "VERIFIER"
      | "expectedChainKey"
      | "expectedSourceSender"
      | "processedQueries"
      | "sourceContract"
      | "verifyAndRecord"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DecisionRecorded" | "VerifiedSignalAccepted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MARKET_SIGNAL_EVENT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VERIFIER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "expectedChainKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "expectedSourceSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processedQueries",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sourceContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndRecord",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      INativeQueryVerifier.MerkleProofStruct,
      INativeQueryVerifier.ContinuityProofStruct,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "MARKET_SIGNAL_EVENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VERIFIER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expectedChainKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expectedSourceSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedQueries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sourceContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndRecord",
    data: BytesLike
  ): Result;
}

export namespace DecisionRecordedEvent {
  export type InputTuple = [
    queryKey: BytesLike,
    action: BigNumberish,
    confidence: BigNumberish,
    riskScore: BigNumberish,
    sourceTxHash: BytesLike
  ];
  export type OutputTuple = [
    queryKey: string,
    action: bigint,
    confidence: bigint,
    riskScore: bigint,
    sourceTxHash: string
  ];
  export interface OutputObject {
    queryKey: string;
    action: bigint;
    confidence: bigint;
    riskScore: bigint;
    sourceTxHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedSignalAcceptedEvent {
  export type InputTuple = [
    queryKey: BytesLike,
    sourceTxHash: BytesLike,
    proofDigest: BytesLike
  ];
  export type OutputTuple = [
    queryKey: string,
    sourceTxHash: string,
    proofDigest: string
  ];
  export interface OutputObject {
    queryKey: string;
    sourceTxHash: string;
    proofDigest: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttestAIDecision extends BaseContract {
  connect(runner?: ContractRunner | null): AttestAIDecision;
  waitForDeployment(): Promise<this>;

  interface: AttestAIDecisionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MARKET_SIGNAL_EVENT: TypedContractMethod<[], [string], "view">;

  VERIFIER: TypedContractMethod<[], [string], "view">;

  expectedChainKey: TypedContractMethod<[], [bigint], "view">;

  expectedSourceSender: TypedContractMethod<[], [string], "view">;

  processedQueries: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  sourceContract: TypedContractMethod<[], [string], "view">;

  verifyAndRecord: TypedContractMethod<
    [
      chainKey: BigNumberish,
      blockHeight: BigNumberish,
      encodedTransaction: BytesLike,
      merkleProof: INativeQueryVerifier.MerkleProofStruct,
      continuityProof: INativeQueryVerifier.ContinuityProofStruct,
      sourceTxHash: BytesLike,
      action: BigNumberish,
      confidence: BigNumberish,
      riskScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MARKET_SIGNAL_EVENT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFIER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "expectedChainKey"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "expectedSourceSender"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processedQueries"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "sourceContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyAndRecord"
  ): TypedContractMethod<
    [
      chainKey: BigNumberish,
      blockHeight: BigNumberish,
      encodedTransaction: BytesLike,
      merkleProof: INativeQueryVerifier.MerkleProofStruct,
      continuityProof: INativeQueryVerifier.ContinuityProofStruct,
      sourceTxHash: BytesLike,
      action: BigNumberish,
      confidence: BigNumberish,
      riskScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DecisionRecorded"
  ): TypedContractEvent<
    DecisionRecordedEvent.InputTuple,
    DecisionRecordedEvent.OutputTuple,
    DecisionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "VerifiedSignalAccepted"
  ): TypedContractEvent<
    VerifiedSignalAcceptedEvent.InputTuple,
    VerifiedSignalAcceptedEvent.OutputTuple,
    VerifiedSignalAcceptedEvent.OutputObject
  >;

  filters: {
    "DecisionRecorded(bytes32,uint8,uint8,uint8,bytes32)": TypedContractEvent<
      DecisionRecordedEvent.InputTuple,
      DecisionRecordedEvent.OutputTuple,
      DecisionRecordedEvent.OutputObject
    >;
    DecisionRecorded: TypedContractEvent<
      DecisionRecordedEvent.InputTuple,
      DecisionRecordedEvent.OutputTuple,
      DecisionRecordedEvent.OutputObject
    >;

    "VerifiedSignalAccepted(bytes32,bytes32,bytes32)": TypedContractEvent<
      VerifiedSignalAcceptedEvent.InputTuple,
      VerifiedSignalAcceptedEvent.OutputTuple,
      VerifiedSignalAcceptedEvent.OutputObject
    >;
    VerifiedSignalAccepted: TypedContractEvent<
      VerifiedSignalAcceptedEvent.InputTuple,
      VerifiedSignalAcceptedEvent.OutputTuple,
      VerifiedSignalAcceptedEvent.OutputObject
    >;
  };
}
