/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AttestAIDecision } from "./AttestAIDecision";
export type { INativeQueryVerifier } from "./INativeQueryVerifier";
